import Header from "./templates/header";
import Head from "next/head";
import Footer from "./templates/footer";
import PopupContact from "./templates/popupContact";
import MobileMenu from "./templates/mobileMenu";

// Основной Layout
export default function Layout({ children }: any) {
    
    return (
    <>
        <Head>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link href="https://fonts.googleapis.com/css?family=Roboto:100,100italic,300,300italic,regular,italic,500,500italic,700,700italic,900,900italic" rel="stylesheet" />
        </Head>
        <Header />
        <MobileMenu />
        <PopupContact />
        {/* <Loading /> */}
        <main className='_main'> 
            <div className="_wrapper">
                { children }
            </div>
        </main>
        <Footer />
    </>
    )
}

